import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";



import Navbar from "./Components/Navbar";

import LastSection from "./Components/LastSection";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Matt Course",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
 
 return (
    
<html lang="en">
      
<body
        
className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      
>
 
<Navbar />       
        
{children}
 
<LastSection/>     
</body>
    
</html>
  
);
}
